name = "akasia"
description = "A minimalistic blog with touch of ivory surfaces with maroon touch"
license = "MIT"
homepage = "https://github.com/edelsora/edelsora.github.io"

# The minimum version of Zola required
min_version = "0.4.0"

# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable

# Use snake_casing to be consistent with the rest of Zola
[extra]
favicon = ""
navigations = []


# The theme author info: you!
[author]
  name = "Yoghaswara HN"
  homepage = "https://edelsora.github.io"
